server:
  port: 9001

spring:
  application:
    name: MEDIA-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
    
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    
    